### ISSUE TITLE
Can lynch killed players

### ISSUE THREAD

**Issue by taliyahpottruff** [taliyahpottruff/game-master#23]
If a player was killed by the GM they are still lynchable.

It might be worth checking if dead is set or if lynching doesn't check for dead.

**Comment by trentonpottruff** [comment]
Killed players appear to be dead in the code, likely a problem with the lynch command

**Comment by taliyahpottruff** [comment]
Fixed in commit https://github.com/taliyahpottruff/game-master/commit/65c7b2b09ebef3f830364cf7ce70e98b6f4aedc5
